<?php /* @var $this Aoe_Searchperience_Block_Adminhtml_System_Config_Fieldset_Info */ ?>
<div class="section-config sp_info">
    <fieldset class="config collapseable">
        <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/kRasSe_ilig?wmode=opaque" frameborder="0" allowfullscreen></iframe>
        <div class="sp_learnmore"><?php echo $this->__('Learn more at <a href="%s" target="_blank">%s</a>', 'http://' . $this->__('searchperience.com'), $this->__('searchperience.com')) ?></div>
    </fieldset>
</div>