<?php /* @var $this Aoe_Searchperience_Block_Adminhtml_System_Config_Fieldset_Info */ ?>
<div class="section-config sp_info">
    <fieldset class="config collapseable">
        <div class="sp_info_column sp_info_column_one">
            <img src="<?php echo $this->getSkinUrl('images/searchperience/pic-performance.jpg') ?>" alt="test" style="float: left" />
            <div>
                <h2><a href="features/apache_solr.html" target="_top">Performance</a></h2>
                <p>With the enterprise search solution Apache Solr at its core, Searchperience enables you to handle even the heaviest visitor traffic and literally millions of documents.</p> <a href="http://www.searchperience.com/features/software_as_a_service.html" target="_blank" class="bu bu-3"><span>Details</span></a>
            </div>
        </div>

        <div class="sp_info_column sp_info_column_right sp_info_column_two">
            <img src="<?php echo $this->getSkinUrl('images/searchperience/pic-chair_03.jpg') ?>" alt="test" style="float: left" />
            <div>
                <h2><a href="features/software_as_a_service.html" target="_top">Search as a Service</a></h2>
                <p>Searchperience brings you all the advantages of Cloud Computing: the search runs on our servers, not yours. There’s nothing to install or implement and no extra work for your IT-department. With minimal effort we can connect this intelligent search to your existing company website or online shop.</p> <a href="http://www.searchperience.com/features/software_as_a_service.html" target="_blank" class="bu bu-3"><span>Details</span></a>
            </div>
        </div>

        <div class="sp_info_column sp_info_column_three">
            <img src="<?php echo $this->getSkinUrl('images/searchperience/pic_robot_03.jpg') ?>" alt="test" style="float: left" />
            <div>
                <h2><a href="features/crawling.html" target="_top">Professional Indexing</a></h2>
                <p>The intelligent Searchperience-Crawler indexes and analyzes your site automatically and at regular intervals. We do not require any data from you! The crawler understands the semantics of your pages and recognizes different page types.</p><a href="http://www.searchperience.com/features/crawling.html" target="_blank" class="bu bu-3"><span>Details</span></a>
            </div>
        </div>
        <div class="sp_info_column sp_info_column_right sp_info_column_four">
            <img src="<?php echo $this->getSkinUrl('images/searchperience/pic-cube_03.jpg') ?>" alt="test" style="float: left" />
            <div>
                <h2><a href="features/facettierung_und_filter.html" target="_top">Facets and Filters</a></h2>
                <p>By clicking on pre-selected filter functions, facetted search enables you to quickly narrow down your results, making search more efficient and satisfying.</p><a href="http://www.searchperience.com/features/facetting_and_filtering.html" target="_blank" class="bu bu-3"><span>Details</span></a>
            </div>
        </div>

        <div class="sp_learnmore"><?php echo $this->__('Learn more at %s', '<a href="http://searchperience.com" target="_blank">searchperience.com</a>') ?></div>
    </fieldset>
</div>