<?php
/** @var Aoe_Searchperience_Helper_Data $aoeSearchperienceHelper */
$aoeSearchperienceHelper = Mage::helper('aoe_searchperience');
?>
<?php if ($aoeSearchperienceHelper->isRecommendationTrackingEnabled()): ?>
<script type="text/javascript">
    var ____tu = '<?php echo $aoeSearchperienceHelper->getRecommendationTrackingScriptUrl() ?>';
    var ____td = ____td || [];
    var ____tq = ____tq || [];
    (function() {
        var tr = document.createElement('script'); tr.type = 'text/javascript'; tr.async = true; tr.src = ____tu + 't.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(tr, s);
    })();
</script>
<?php endif; ?>
