<?php
/** @var Aoe_Searchperience_Helper_Data $aoeSearchperienceHelper */
$aoeSearchperienceHelper = Mage::helper('aoe_searchperience');
?>
<?php if ($aoeSearchperienceHelper->isWidgetFeatureEnabled()): ?>
<script type="text/javascript">
    var ____tu = '<?php echo $aoeSearchperienceHelper->getWidgetsScriptUrl() ?>';
    (function() {
        var tr = document.createElement('script'); tr.type = 'text/javascript'; tr.async = true; tr.src = ____tu;
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(tr, s);
    })();
</script>
<?php endif; ?>
