<?php
/** @var Aoe_Searchperience_Helper_Data $aoeSearchperienceHelper */
$aoeSearchperienceHelper = Mage::helper('aoe_searchperience');
?>
<?php if ($aoeSearchperienceHelper->isWidgetFeatureEnabled()): ?>
<script type="text/javascript">
    (function() {
        var srcUrl = '<?php echo $aoeSearchperienceHelper->getWidgetsScriptUrl() ?>';
        var tr = document.createElement('script'); tr.type = 'text/javascript'; tr.async = true; tr.src = srcUrl;
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(tr, s);
    })();
</script>
<?php endif; ?>
